spring.application.name=student-management

spring.datasource.url=jdbc:postgresql://localhost:5432/student-management
spring.datasource.username=thuanle
spring.datasource.password=thuanle
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# ========================
# JWT Configuration
# ========================
jwt.secret=JPY7+Ri1eIKStdOBgzyhx5a0GdHH4PAHBykqMwQAD7c=
jwt.expiration=3600000

# ========================
# i18n
# ========================
spring.messages.encoding=UTF-8
spring.messages.basename=i18n/messages

# ========================
# LOGGING CONFIG (PRODUCTION)
# ========================

# Log level
logging.level.root=INFO
logging.level.com.thuannluit=DEBUG
logging.level.org.springframework=INFO
logging.level.org.hibernate=INFO

# Tắt log SQL mặc định (tránh spam)
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.type.descriptor.sql=OFF

# Log file
logging.file.name=logs/student-management.log

# Pattern JSON (console)
logging.pattern.console=%d{HH:mm:ss} [%p] [%X{requestId}] %m%n
# Pattern JSON (file)
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%p] [%X{requestId}] %m%n

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger

# ========================
# KAFKA CONFIG
# ========================
spring.kafka.bootstrap-servers=localhost:9092
kafka.topic.name=student-events
kafka.auth.topic.name=auth-events

# Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.retries=3

# Consumer
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# Common
spring.kafka.producer.properties.spring.json.type.mapping=event:com.thuannluit.student_management.event.StudentEvent,authEvent:com.thuannluit.student_management.event.AuthEvent
spring.kafka.consumer.properties.spring.json.type.mapping=event:com.thuannluit.student_management.event.StudentEvent,authEvent:com.thuannluit.student_management.event.AuthEvent

# ========================
# MAIL CONFIG (Gmail SMTP)
# ========================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=bavuonghocduongk42@gmail.com
spring.mail.password=wlmo aehc wgqw giil
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Email sender
app.mail.from=bavuonghocduongk42@gmail.com