spring.application.name=student-management

spring.datasource.url=jdbc:postgresql://localhost:5432/student-management
spring.datasource.username=thuanle
spring.datasource.password=thuanle
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
jwt.secret=JPY7+Ri1eIKStdOBgzyhx5a0GdHH4PAHBykqMwQAD7c=
jwt.expiration=3600000
